// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Thuc_tap_tuan2.DbContexts;

#nullable disable

namespace Thuc_tap_tuan2.Migrations
{
    [DbContext(typeof(Data))]
    [Migration("20240813052130_DbInit")]
    partial class DbInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Thuc_tap_tuan2.Entities.DoanhNghiep", b =>
                {
                    b.Property<int>("IdDN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDN"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MST")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenDN")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdDN");

                    b.HasIndex("MST")
                        .IsUnique();

                    b.HasIndex("TenDN")
                        .IsUnique();

                    b.ToTable("doanhnghiep", (string)null);
                });

            modelBuilder.Entity("Thuc_tap_tuan2.Entities.DoanhNghiepSanPham", b =>
                {
                    b.Property<int>("IdSP")
                        .HasColumnType("int");

                    b.Property<int>("IdDN")
                        .HasColumnType("int");

                    b.Property<int>("Soluong")
                        .HasColumnType("int");

                    b.HasKey("IdSP", "IdDN");

                    b.HasIndex("IdDN");

                    b.ToTable("doanhnghiepsanpham", (string)null);
                });

            modelBuilder.Entity("Thuc_tap_tuan2.Entities.SanPham", b =>
                {
                    b.Property<int>("IdSP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSP"));

                    b.Property<string>("MaSp")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenSp")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdSP");

                    b.HasIndex("MaSp")
                        .IsUnique();

                    b.HasIndex("TenSp")
                        .IsUnique();

                    b.ToTable("sanpham", (string)null);
                });

            modelBuilder.Entity("Thuc_tap_tuan2.Entities.DoanhNghiepSanPham", b =>
                {
                    b.HasOne("Thuc_tap_tuan2.Entities.DoanhNghiep", "DoanhNghiep")
                        .WithMany("DoanhNghiepSanPhams")
                        .HasForeignKey("IdDN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("Fk_doanhnghiep");

                    b.HasOne("Thuc_tap_tuan2.Entities.SanPham", "SanPham")
                        .WithMany("DoanhNghiepSanPhams")
                        .HasForeignKey("IdSP")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("Fk_sanpham");

                    b.Navigation("DoanhNghiep");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("Thuc_tap_tuan2.Entities.DoanhNghiep", b =>
                {
                    b.Navigation("DoanhNghiepSanPhams");
                });

            modelBuilder.Entity("Thuc_tap_tuan2.Entities.SanPham", b =>
                {
                    b.Navigation("DoanhNghiepSanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
